apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/fluxcd/source-controller/config/default?ref=53194ad4730ebf07718b29d58f66efd6938fd3da # v1.9.5
- serviceaccount.yaml
- networkpolicy.yaml

labels:
- pairs:
    app.kubernetes.io/component: source-controller
  includeSelectors: true

images:
- name: fluxcd/source-controller
  newName: ghcr.io/fluxcd/source-controller

patches:
- path: patches/delete_namespace.yaml
- path: patches/use_serviceaccount.yaml
- path: patches/set_resources_limits_requests.yaml
