apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: traefik
    app.kubernetes.io/managed-by: Helm
spec:
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
